#                 .__               .__
# _______  ______ |  |  __ __  ____ |__| ____   ______
# \_  __ \ \____ \|  | |  |  \/ ___\|  |/    \ /  ___/
#  |  | \/ |  |_> >  |_|  |  / /_/  >  |   |  \\___ \
#  |__|    |   __/|____/____/\___  /|__|___|  /____  >
#          |__|             /_____/         \/     \/
#



# Нужна помощь или хочешь узнавать и предлагать идеи для обновлений?
# ТГК: https://t.me/reqqpeDev


#Настройки пула соединений, если не знаете что это рекомендуется не менять
database:
  max-pool-size: 10
  #В миллисекундах
  keep-alive: 120000
  idle-timeout: 60000
  connection-timeout: 30000
  max-life-time: 1800000


# Какое меню будет открывать команда /<buyer|seller|sell>
sell-command: "mainGUI" # Такие же названия как у GUI файлов (allSellGUI, mainGUI, autoSellGUI)


metrics: true
update-check: true


autosell:
  enable: true # Переключение работает только при перезагрузке сервера
  # Тип авто-скупки, если установить false раз в какое-то время будет проверяться каждый игрок на сервере
  # и будет вызываться метод авто-скупки(очень не оптимизированное решение), если будет true метод авто-скупки будет
  # вызываться только при подборе предметов
  optimization: true # Переключение работает только при перезагрузке сервера
  check-interval-tick: 40 # Раз в сколько тиков будет проверяться инвентарь. 20 тиков - 1 секунда
  start_category: resources # Категория, которая будет открываться при первом открытие
  categories:
    all:
      name: "Все предметы"
      items:
        - all
    resources:
      name: "Ресурсы"
      items:
        - COAL
        - LAPIS_LAZULI
        - IRON_INGOT
        - GOLD_INGOT
        - DIAMOND
        - EMERALD
        - NETHERITE_INGOT
numbers_format:
  # https://github.com/reqqpe/rSeller/wiki/Руководство-по-настройке-формата-чисел
  placeholders:
    points: "%.2f"
    points_needed: "%.2f"
    multiplier_points: "%.2f"
    multiplier_coins: "%.2f"
    points_fornextlevel: "%.2f"
  mainGUI:
    sell_price: "%.2f"
    sell_points: "%.2f"
  autoSellGUI:
    sell_price: "%.2f"
    sell_points: "%.2f"
  messages:
    points: "%.2f"
    coins: "%.2f"


# Бустеры по пермишенам rseller.booster.<key>
boosters:

  # Не забывайте, если вы укажите donate.vip, то конфигурация будет не правильная (так работает yaml)
  # Так же если у вас все права, то значит и все бустеры (что не странно потому что они же работают на правах)

  
  donate: # Пермишен rseller.booster.donate
    coin-multiplier: 2.0 # Если не указывать, то изначально 1.0
    point-multiplier: 2.0 # Если не указывать, то изначально 1.0

  booster-coin: # rseller.booster.booster-coin
    coin-multiplier: 1.5

  booster-point:
    point-multiplier: 1.5



levels:
  1:
    coin-multiplier: 1.0
    point-multiplier: 1.0
    required-points: 0.0
  2:
    coin-multiplier: 1.1
    point-multiplier: 1.1
    required-points: 100.0
  3:
    coin-multiplier: 1.2
    point-multiplier: 1.1
    required-points: 250.0
  4:
    coin-multiplier: 1.3
    point-multiplier: 1.2
    required-points: 500.0

messages:
  reload:
    all: "&aПлагин успешно перезагружен"
    guis: "&aКонфигурация менюшек успешно перезагружена"
    items: "&aКонфигурация предметов успешно перезагружена"
    config: "&aГлавная конфигурация успешно перезагружена"
  no-permission: "&cУ вас нет прав использовать эту команду"
  no-arguments: "&cНе достаточно аргументов"
  points-usage: "&cИспользование: /sa points <add/remove/set> <кол-во> [игрок]"
  un-int: "&cВы указали неверное число: {value}"
  not-found-player: "&cНе удалось найти игрока"
  update-points-sender: "&aУ игрока &f{player} &aтеперь &f{value} &aочков прокачки"
  update-points-target: "&aВаши очки прокачки были обновлены до &f{value}"
  no-sell-items: "&cНет предметов, которые можно продать"
  sell-items: "&aВы успешно продали предметы на сумму {coins} и получили {points} очков"
  auto-sell: "&aАвтоскупка: {coins}$ и {points} очков начислено."
  usage-auto-sell: "&cИспользование: /autosell <материал>"
  not-found-material: "&cНеизвестный материал"
  autosell-enable: "&aвключена"
  autosell-disable: "&cвыключена"
  autosell-message: "&7Автоскупка для &e{material} &7{status}"
  negative-value: "&cНельзя использовать отрицательные значения!"
  negative-set: "&cНельзя установить отрицательное количество поинтов!"
  not-enough-points: "&cУ игрока недостаточно поинтов! Текущие: {current}"
  not-item-in-conf: "&cНе удалось включить авто продажу для этого предмета"
  already-exists-item: "&cНе удалось создать предмет такой айди уже существует"
  only-player: "&cЭту команду может использовать только игрок"
  no-item: "&cПохоже в вашей руке нет предмета, возьмите предмет в руку чтобы создать"
  create-success: "&aПредмет успешно создан и записан в конфигурацию"
