#                 .__               .__
# _______  ______ |  |  __ __  ____ |__| ____   ______
# \_  __ \ \____ \|  | |  |  \/ ___\|  |/    \ /  ___/
#  |  | \/ |  |_> >  |_|  |  / /_/  >  |   |  \\___ \
#  |__|    |   __/|____/____/\___  /|__|___|  /____  >
#          |__|             /_____/         \/     \/
#



#Настройки пула соединений, если не знаете что это рекомендуется не менять
database:
  max-pool-size: 10
  #В миллисекундах
  keep-alive: 120000
  idle-timeout: 60000
  connection-timeout: 30000
  max-life-time: 1800000

autosell:
  enable: true # Переключение работает только при перезагрузке плагина
  check-interval-tick: 40 # Раз в сколько тиков будет проверяться инвентарь. 20 тиков - 1 секунда

levels:
  1:
    coin-multiplier: 1.0
    point-multiplier: 1.0
    required-points: 0.0
  2:
    coin-multiplier: 1.1
    point-multiplier: 1.1
    required-points: 100.0
  3:
    coin-multiplier: 1.2
    point-multiplier: 1.1
    required-points: 250.0
  4:
    coin-multiplier: 1.3
    point-multiplier: 1.2
    required-points: 500.0

messages:
  reload: "&aПлагин успешно перезагружен"
  no-permission: "&cУ вас нет прав использовать эту команду"
  no-arguments: "&cНе достаточно аргументов"
  points-usage: "&cИспользование: /sa points <add/remove/set> <кол-во> [игрок]"
  un-int: "&cВы указали неверное число: {value}"
  not-found-player: "&cНе удалось найти игрока"
  update-points-sender: "&aУ игрока &f{player} &aтеперь &f{value} &aочков прокачки"
  update-points-target: "&aВаши очки прокачки были обновлены до &f{value}"
  no-sell-items: "&cНет предметов, которые можно продать"
  sell-items: "&aВы успешно продали предметы на сумму {coins} и получили {points} очков"
  auto-sell: "&aАвтоскупка: {coins}$ и {points} очков начислено."
  usage-auto-sell: "&cИспользование: /autosell <материал>"
  not-found-material: "&cНеизвестный материал"
  autosell-enable: "&aвключена"
  autosell-disable: "&aвыключена"
  autosell-message: "&7Автоскупка для &e{material} &7{status}"
  negative-value: "&cНельзя использовать отрицательные значения!"
  negative-set: "&cНельзя установить отрицательное количество поинтов!"
  not-enough-points: "&cУ игрока недостаточно поинтов! Текущие: {current}"
  not-item-in-conf: "&cНе удалось включить авто продажу для этого предмета"
